const actionTypes = {
    GET_SHOW_CONTENT: 'GET_SHOW_CONTENT',
    SET_SHOW_CONTENT: 'SET_SHOW_CONTENT',
    GET_SHOW_CONTENT_ERROR: 'GET_SHOW_CONTENT_ERROR',
    SELECT_EPISODE: 'SELECT_EPISODE',
    GET_SHOW_EPISODES: 'GET_SHOW_EPISODES',
    SET_SHOW_EPISODES: 'SET_SHOW_EPISODES',
    GET_EPISODE_DETAILS: 'GET_EPISODE_DETAILS',
    SET_ERROR: 'SET_ERROR',
    SET_SELECTED_EPISODE: 'SET_SELECTED_EPISODE',
};

export default actionTypes;
